version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: unitymicrofund-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "123AsD,./"
      MARIADB_DATABASE: microfundDb
      MARIADB_USER: microfund
      MARIADB_PASSWORD: "123AsD,./"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
